### ISSUE TITLE
type 'FusedTransformer' is not a subtype of type 'SyncTransformer' in type cast

### ISSUE THREAD

**Issue by SunilKividor** [movebuilder/aptos#9]
all the future methods return this error. Is there something I am missing or doing anything wrong.
Below is my code which I am using 
`   const privateKey = "";
    const String maxGasAmount = '64780';
    const String gasPrice = '54780';
    const String amount = '1044780';
    const receiverAddress = "0x66a77185e5ad0c5687017797b8702ea001d5a3e8aa2da49577d4629bb23162b6";
    final expirationTimestamp = BigInt.from(DateTime.now().millisecondsSinceEpoch ~/ 1000 + 600);
    final aptos = AptosClient(Constants.mainnetAPI, enableDebugLog: true);
    final account = AptosAccount(Uint8List.fromList(HEX.decode(privateKey)));
    final sender = account.address;
    final accountInfo = await aptos.getAccount(sender);
    logger.d(accountInfo.sequenceNumber);

    final txSubmission = TransactionEncodeSubmissionRequest(
      sender: sender,
      sequenceNumber: accountInfo.sequenceNumber,
      maxGasAmount: maxGasAmount,
      gasUnitPrice: gasPrice,
      expirationTimestampSecs: expirationTimestamp.toString(),
      payload: Payload(
          type: "entry_function_payload",
          function: "0x1::coin::transfer",
          typeArguments: ["0x1::aptos_coin::AptosCoin"],
          arguments: [receiverAddress, amount]
      )
    );

    final encodeTx = await aptos.encodeSubmission(txSubmission);
    final hex = HEX.decode(encodeTx.substring(2));
    final hexBytes = Uint8List.fromList(hex);
    final privateKeyBytes = HexString(privateKey).toUint8Array();
    final signingKey = ed25519.PrivateKey(privateKeyBytes);
    final signEncode = ed25519.sign(signingKey, hexBytes).sublist(0, 64);

    final tx = TransactionRequest(
        sender: txSubmission.sender,
        sequenceNumber: txSubmission.sequenceNumber,
        maxGasAmount: txSubmission.maxGasAmount.toString(),
        gasUnitPrice: txSubmission.gasUnitPrice.toString(),
        expirationTimestampSecs: txSubmission.expirationTimestampSecs.toString(),
        payload: txSubmission.payload,
        signature: Signature(
          type: "ed25519_signature",
          publicKey: account.pubKey().hex(), 
          signature: "0x"+HEX.encode(signEncode)
        )
    );

    final result = await aptos.submitTransaction(tx);`

**Comment by 0xmove** [comment]
fixed in v0.0.6
